### ISSUE TITLE
Bentham calculus encourages agents to move to low value cells

### ISSUE THREAD

**Issue by colinhanrahan** [nkremerh/sugarscape#114]
When experimenting with Bentham agents with infinite vision/movement, I noticed that many of them were moving to the very edges of the sugarscape rather than the center as expected. Here's a visualization of calculated ethical scores for the first agent to move in one of my sims:
<img width="502" alt="Screenshot 2024-07-27 at 4 57 52 PM" src="https://github.com/user-attachments/assets/7f72e7a8-b4b2-4440-91b3-30710e06b75f">
I've normalized scores from red (worst) to green (best). It's clear that agents are being encouraged to move to cells with lower ethical scores. Here's a rough example for why I think this is happening:

value of cell is **0.5**
10 neighbors
ethical score = 0.5 - 10(0.5) = **-4.5**

value of cell is **0.25**
10 neighbors
ethical score = 0.25 - 10(0.25) = **-2.25**

The values aren't realistic but display the issue. Another piece of evidence contributing to this is that sims with only one agent seem to work correctly because there are no opportunity costs to subtract:
<img width="497" alt="Screenshot 2024-07-27 at 5 49 54 PM" src="https://github.com/user-attachments/assets/2f0c871c-9298-4633-9ce9-f91e7689f5ed">

@nkremerh What are your thoughts on this?

**Comment by nkremerh** [comment]
This makes sense when agents can see the entire map. They will go to cells where they inconvenience nobody. When constrained to a far more local neighborhood, they don't have the opportunity to escape to the far-flung corners of the world. Instead, they have to determine the best _local_ cell with the knowledge that they will cause _some_ harm (at the moment, agents feel no remorse for this, but that could be an interesting topic for future study).
