### ISSUE TITLE
Long runs have a large memory footprint

### ISSUE THREAD

**Issue by nkremerh** [nkremerh/sugarscape#17]
Running the simulation in excess of 1,000 timesteps (given a successful seed with a thriving population) leads to a large memory footprint (> 8GB). There is likely one or more significant memory inefficiencies at play that should be diagnosed and patched. This will eliminate a bottleneck preventing more simulations running in parallel during data collection.

**Comment by colinhanrahan** [comment]
On my test with `benthamHalfLookaheadBinary`, at 1000 timesteps, there were 2 million dictionaries taking up half a gigabyte of memory. The memory graph is consistently going up. Looks like they aren't being garbage collected — I'll look into this further.

**Comment by colinhanrahan** [comment]
Preliminary results: it seems to be that the social networks are keeping references to dead agents, which still have their own social networks which keep references, etc. so they build up over time. I removed everything from dead agents' social networks except children and debtors (which are still needed) and the number of dictionaries at 1000 timesteps went from 2 million to 350,000. I still need to check to see if the simulation behaves the same. I'm going to do a small overhaul of interaction between dead agents and social networks and see what happens.

**Comment by colinhanrahan** [comment]
Update: The memory leak is mostly, solved, but the memory usage is still slowly increasing over time. Most, if not all, of the remaining dictionaries are loans whose references are somehow avoiding removal.

**Comment by nkremerh** [comment]
Solved by #39.
