### ISSUE TITLE
Simulation run should allow a mixture of decision models

### ISSUE THREAD

**Issue by nkremerh** [nkremerh/sugarscape#21]
It would be useful if the user could specify an array of decision models in the configuration file. If a decision model is listed more than once in the array, consider this an indication it should be more prevalent in the starting population. Otherwise, if all models in the array are only listed once, seed the starting population with a (roughly) even distribution of the decision models. This would allow for more realistic and richer societies during data collection.

**Comment by colinhanrahan** [comment]
What about a dictionary with weights for each decision model? You could set one model to 1 and another to 2 for a 2:1 ratio, or set one to 0.25 and another to 0.75 if you want to represent them as percentages.

**Comment by nkremerh** [comment]
That would be feasible (it's a good idea), but there are a couple design reasons we've avoided that route:

1. We want options to be as simple as possible. We're already at two JSON objects deep with the current options, and I'd like to avoid making it three objects deep. The solution as proposed in the issue description also ensures the option in the config continues to look like the others. It's not a lift for a new user to understand how to pass in values to the option.

2. Using a dictionary would make agentDecisionModel behave differently from most options. We spent a fair bit of effort reworking how agent configuration is handled in the simulation to have a (more or less) unified mechanism for doling out agent attributes. I want to keep the exceptions to that mechanism as few as possible (or have a new unified mechanism to handle everything which seems like a harder problem).

**Comment by colinhanrahan** [comment]
That sounds good. Is agentDecisionModelData intended for this feature, or should agentDecisionModel be changed to an array of model strings?

**Comment by nkremerh** [comment]
We should change agentDecisionModel to be an array of strings. The agentDecisionModelData option is a placeholder which currently does nothing.

**Comment by nkremerh** [comment]
Added in b247906. Closing issue but awaiting thorough testing.
