### ISSUE TITLE
Model naming and implementations don't match up?

### ISSUE THREAD

**Issue by colinhanrahan** [nkremerh/sugarscape#40]
I'm not sure if the naming and the ethical weighting systems match up. In `ethics.py`, `altruistic*` models multiply their own ethical weights by 0, placing no ethical value on themselves. This seems to line up more with "selflessness" than altruism, which should place equal importance on the wellbeing of every agent — including the current agent. Likewise, standard `bentham*` models multiply all agents' scores, including the current agent, by a factor of 0.5. This places equal weight on the current agent and other agents, which doesn't seem correct for a "selfishness factor" of 0.5. That sounds like what `altruistic*` should be.

There are two ways to fix this:

_1. Remove selflessness._
- Instead of multiplying `self` scores by `selfishnessFactor` and `neighbor` scores by `(1 - selfishnessFactor)`, only multiply `neighbor` scores by `(1 - selfishnessFactor)` and keep the `self` score the same.
- Now `altruistic*` models will be altruistic and `bentham*` models will be slightly selfish, which I think is the intended behavior.

_2. Include selflessness (technically the behavior we have right now)._
- Keep the current formula for calculating `self` vs. `neighbor` scores in `ethics.py`.
- Consider a new `selfless*` model with a `selfishnessFactor` of 0 that discards its own value in ethical calculations.
- Move `altruistic*` models to have a `selfishnessFactor` of 0.5 so they place equal weight on all agents.
- Move `bentham*` models to have a `selfishnessFactor` of 0.75 so they consider their own outcomes slightly more than other agents.
You could also vary between -1 and 1 for better readability, but we're already using -1 to indicate no selfishness factor.

@nkremerh please let me know what you think.

**Comment by nkremerh** [comment]
Short answer:
Everything is working as intended.

Long answer:
An altruist agent cares _only_ about the consequences for everyone else. Altruist agents should completely disregard their own wellbeing in deference to their neighborhood's wellbeing. This matches with a `selfishnessFactor` of 0.

A utilitarian (in the Bentham sense) agent places equal weight to the consequences for all agents. They consider their own consequences, but they don't value them any more than the consequences of another. This matches with a `selfishnessFactor` of 0.5 (and also a `selfishnessFactor` of -1 as a backwards compatibility value).

A purely egoist agent has a `selfishnessFactor` of 1 and concerns themselves _only_ with their own consequences.

A `selfishnessFactor` between 0 and 0.5 is a progressively less altruistic but still neighborhood-focused agent. A `selfishnessFactor` between 0.5 and 1 is a progressively more egoistic but still neighborhood-considerate agent.
