### ISSUE TITLE
UBI placement during an agent's timestep leads to bugs

### ISSUE THREAD

**Issue by nkremerh** [nkremerh/sugarscape#51]
Issue is hotfixed in cd26c63.

Depending on the placement of the `doUniversalBasicIncome` method in the agent's `doTimestep` method, some weird behavior either occurs or never shows. When UBI is handed out before `moveToBestCell`, the bugged behaviors below occur. When UBI is handed out after `moveToBestCell`, there are no bugged agents.

Agents are sometimes choosing their own cell as the best place to move (which is only allowed as a last resort but was happening when other choices existed). Agents are sometimes getting evicted from their cell while still being alive (allowing the population to grow past the number of cells).

Simply moving the UBI to _after_ `moveToBestCell` but _before_ `doMetabolism` (and the rest of the timestep) was sufficient for fixing the behavior without breaking UBI.

The root cause for this bug is likely to be some edge case(s) in the `moveToBestCell` method or other methods it calls. It is likely getting stress tested by UBI in ways not present with the other simulation options. Fixing the root cause (even if it _is_ in UBI) will close up any edge cases which may affect future features.

**Comment by colinhanrahan** [comment]
For more context, what does "eviction" mean? Are agents disappearing from the map, or are there sometimes multiple agents in a cell, or something else?

**Comment by nkremerh** [comment]
An agent has a reference to a cell in the environment. A cell likewise has a reference to the agent currently at that cell.

Eviction here means an agent moves to a cell in a timestep, but at some point (either before the conclusion of their turn or by the time it is their turn again) the reference to that agent is lost at the cell. The agent is still alive and may move to a new cell since it still has a reference to their old cell (i.e. `agent.cell != None` but `cell.agent == None` or `cell.agent ==` some other agent).

This means the total population can grow beyond the hard limit of the number of cells in the environment. Additionally, evicted agents are safe from any combat and cannot participate in trade, lending, or reproduction until their next move.

**Comment by colinhanrahan** [comment]
Update: I've found very few evictions, but every one that I have found is related to a diseased agent. I couldn't find a single eviction in 25 seeds with UBI on and disease off. Maybe we are only seeing more evictions with UBI because UBI influences the spread of disease?

**Comment by nkremerh** [comment]
You're likely right that this has something to do with disease and UBI making endemic disease an almost sure thing when the UBI is high enough.

The behavior should be fixed (or very rare) at the current head. If you go back a couple commits, the behavior is more evident. I don't have the specific configs that were causing the issues anymore (lost in the expediency of collecting more data on a multi-GB dataset). But, I was getting around 10 seeds out of 100 that were displaying the behavior from a config @mmilkowski36 sent me. @mmilkowski36 please send @colinhanrahan a sample config for your UBI data collection and instructions on how to use it.

**Comment by nkremerh** [comment]
Resolved by #52.
