### ISSUE TITLE
findWelfare() incorrectly returns 0 when environment only has one resource and tribes are turned on

### ISSUE THREAD

**Issue by colinhanrahan** [nkremerh/sugarscape#64]
I found this during testing for `cultural_tagging.json`. If there is only one resource, the other resource's `*MetabolismProportion` will be 0, so that resource will multipy into `welfare` as `0 ** 0` (just 1). However, when tribes are included, the `*TagPreferences` value will be _nonzero_, so the updated welfare will include 0 to a nonzero power. This makes `findWelfare()` return 0 for all cells, so agents move in a random direction close to them with no useful information about the resources they are gathering. In practice, tribal agents are blind with functional range 1.

As a side note, tribe-based welfare is added near the end of the book (page 124), after most of the examples. Even if we fix this bug, all of our example simulations that include tribes will be adversely affected by this feature. Welfare is modified in a random and often unhelpful way by an agent's tribe, so they are forced to make bad decisions. Fixing this would require adding a config option.

**Comment by nkremerh** [comment]
Go ahead and add the configuration option for this one. Let's call it `agentTagPreferences` where it's a Boolean value. True indicates to use tag-based (tribe-based) preferences for resources. False indicates no tag-based preferences are used.

If I'm reading the code correctly, this should be reflected in line 1034 in `findWelfare` and as a new attribute for the agent.
